name: Deploy Jaspr to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Build Jaspr
        run: |
          dart pub global activate jaspr_cli
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          # Menggunakan perintah sederhana sesuai panduan resmi
          jaspr build --verbose

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Pastikan folder output sesuai dengan standar jaspr build
          path: 'build/jaspr'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4